# DemonFF - Blender scripts for working with Renderware & R*/SA-MP/open.mp formats in Blender
# 2023 - 2026 spicybung

import os

import bpy
from bpy_extras.io_utils import ImportHelper

from ..ops import mta_io


class MTAResourceSettings(bpy.types.PropertyGroup):
    resource_name: bpy.props.StringProperty(
        name="Resource Name",
        default="demonff_mta_resource",
    )

    author: bpy.props.StringProperty(
        name="Author",
        default="",
    )

    description: bpy.props.StringProperty(
        name="Description",
        default="Generated by DemonFF",
    )

    model_mode: bpy.props.EnumProperty(
        name="Model IDs",
        items=(
            (
                "REQUEST_NEW",
                "Allocate Custom IDs",
                "Use engineRequestModel and logical model names. This is the safest mode for custom models.",
            ),
            (
                "REPLACE_EXISTING",
                "Replace Existing IDs",
                "Use fixed target model IDs and engineReplaceModel.",
            ),
        ),
        default="REQUEST_NEW",
    )

    export_scope: bpy.props.EnumProperty(
        name="Export Scope",
        items=(
            ("SCENE", "Complete Scene", "Export all map/model placements in the scene"),
            ("SELECTED", "Selected Objects", "Export selected map/model placements"),
            ("ACTIVE_COLLECTION", "Active Collection", "Export placements in the active collection and its children"),
        ),
        default="SCENE",
    )

    export_placements: bpy.props.BoolProperty(
        name="Export Placements",
        description="Write placements.lua and create the placed objects when the MTA resource starts",
        default=True,
    )

    collision_mode: bpy.props.EnumProperty(
        name="Collision",
        items=(
            (
                "SEPARATE",
                "Separate COL",
                "Export MTA-style separate COL files and load them with engineLoadCOL/engineReplaceCOL",
            ),
            (
                "EMBEDDED",
                "Embedded SA-MP Collision",
                "Embed SA-MP collision in each DFF and omit separate COL files",
            ),
            (
                "NONE",
                "No Collision Export",
                "Do not export or copy collision files",
            ),
        ),
        default="SEPARATE",
    )

    export_dff: bpy.props.BoolProperty(
        name="Export DFF",
        description="Export the scene model groups as MTA-compatible DFF files",
        default=True,
    )

    export_txd: bpy.props.BoolProperty(
        name="Export TXD",
        description="Build TXD files from textures loaded in Blender",
        default=True,
    )

    copy_existing_assets: bpy.props.BoolProperty(
        name="Copy Existing Assets",
        description="Copy missing DFF, TXD, or COL files from the source asset directory",
        default=True,
    )

    source_assets_directory: bpy.props.StringProperty(
        name="Source Assets",
        description="Optional directory containing existing DFF, TXD, and COL files",
        subtype="DIR_PATH",
        default="",
    )

    default_parent_model_id: bpy.props.IntProperty(
        name="Parent Model ID",
        description="Base object model used by engineRequestModel when no per-object override is set",
        default=1337,
        min=1,
    )

    replacement_start_id: bpy.props.IntProperty(
        name="Replacement ID Start",
        description="First fixed model ID assigned when Replace Existing IDs is selected",
        default=1337,
        min=1,
    )

    default_interior: bpy.props.IntProperty(
        name="Default Interior",
        default=0,
        min=0,
    )

    default_dimension: bpy.props.IntProperty(
        name="Default Dimension",
        default=0,
        min=-1,
        max=65535,
    )

    use_map_interior: bpy.props.BoolProperty(
        name="Use Imported Interior",
        description="Use the imported IPL interior value unless an MTA override is set",
        default=True,
    )

    default_lod_distance: bpy.props.FloatProperty(
        name="LOD Distance",
        default=300.0,
        min=0.0,
    )

    skip_lod: bpy.props.BoolProperty(
        name="Skip LOD Objects",
        default=True,
    )

    write_map_file: bpy.props.BoolProperty(
        name="Write placements.map",
        description="Also write an MTA map XML file. Available for fixed replacement IDs only.",
        default=False,
    )

    create_zip: bpy.props.BoolProperty(
        name="Create Resource ZIP",
        default=True,
    )

    clean_output: bpy.props.BoolProperty(
        name="Clean Existing Resource",
        description="Delete the existing resource folder before exporting",
        default=True,
    )

    fail_on_missing_models: bpy.props.BoolProperty(
        name="Fail on Missing DFF",
        description="Cancel the resource export if any placement has no exported or copied DFF",
        default=True,
    )

    write_model_ids_to_scene: bpy.props.BoolProperty(
        name="Store Fixed IDs in Scene",
        description="Write automatically assigned replacement model IDs back to Blender objects",
        default=True,
    )

    truncate_frame_names: bpy.props.BoolProperty(
        name="Truncate Frame Names",
        description="Truncate DFF frame names for compatibility",
        default=False,
    )

    import_collection_name: bpy.props.StringProperty(
        name="Import Collection",
        default="MTA Import",
    )

    import_use_models: bpy.props.BoolProperty(
        name="Use Already-Imported Models",
        description="Duplicate matching model collections already present in Blender",
        default=True,
    )

    import_resource_models: bpy.props.BoolProperty(
        name="Import Resource DFFs",
        description="Import DFF and matching TXD files from an MTA resource when the model is not already in Blender",
        default=True,
    )

    import_placeholders: bpy.props.BoolProperty(
        name="Create Missing Placeholders",
        description="Create an empty object when an imported MTA model cannot be matched",
        default=True,
    )

    import_clear_existing: bpy.props.BoolProperty(
        name="Clear Import Collection",
        default=False,
    )


class MTAObjectSettings(bpy.types.PropertyGroup):
    model_key: bpy.props.StringProperty(
        name="Model Key",
        description="Logical MTA model name. Blank uses the DemonFF DFF/IDE model name.",
        default="",
    )

    target_model_id: bpy.props.IntProperty(
        name="Target Model ID",
        description="Fixed MTA model ID. Zero allows the resource exporter to assign one.",
        default=0,
        min=0,
    )

    parent_model_id: bpy.props.IntProperty(
        name="Parent Model ID",
        description="Base object model for engineRequestModel",
        default=1337,
        min=1,
    )

    use_custom_interior: bpy.props.BoolProperty(
        name="Override Interior",
        default=False,
    )

    interior: bpy.props.IntProperty(
        name="Interior",
        default=0,
        min=0,
    )

    use_custom_dimension: bpy.props.BoolProperty(
        name="Override Dimension",
        default=False,
    )

    dimension: bpy.props.IntProperty(
        name="Dimension",
        default=0,
        min=-1,
        max=65535,
    )

    lod_distance: bpy.props.FloatProperty(
        name="LOD Distance",
        description="Zero uses the IDE draw distance or resource default",
        default=0.0,
        min=0.0,
    )

    double_sided: bpy.props.BoolProperty(
        name="Double Sided",
        default=False,
    )

    collisions_enabled: bpy.props.BoolProperty(
        name="Collisions Enabled",
        default=True,
    )

    frozen: bpy.props.BoolProperty(
        name="Frozen",
        default=True,
    )

    breakable: bpy.props.BoolProperty(
        name="Breakable",
        default=False,
    )

    alpha: bpy.props.IntProperty(
        name="Alpha",
        default=255,
        min=0,
        max=255,
    )

    alpha_transparency: bpy.props.BoolProperty(
        name="DFF Alpha Transparency",
        description="Pass alphaTransparency=true to engineReplaceModel",
        default=True,
    )

    filtering_enabled: bpy.props.BoolProperty(
        name="TXD Filtering",
        description="Enable the engineLoadTXD filtering option",
        default=False,
    )


class EXPORT_OT_mta_resource(bpy.types.Operator):
    bl_idname = "scene.demonff_export_mta_resource"
    bl_label = "Export MTA Resource"
    bl_description = "Export DFF/TXD/COL files, Lua loaders, placements, and meta.xml as an MTA resource"
    bl_options = {"REGISTER"}

    directory: bpy.props.StringProperty(
        name="Output Directory",
        subtype="DIR_PATH",
        options={"HIDDEN"},
    )

    filter_folder: bpy.props.BoolProperty(
        default=True,
        options={"HIDDEN"},
    )

    def invoke(self, context, event):
        if bpy.data.filepath:
            self.directory = os.path.dirname(bpy.data.filepath)
        context.window_manager.fileselect_add(self)
        return {"RUNNING_MODAL"}

    def execute(self, context):
        settings = context.scene.mta
        output_directory = self.directory
        if not output_directory:
            self.report({"ERROR"}, "No output directory selected")
            return {"CANCELLED"}

        options = {
            "output_directory": output_directory,
            "resource_name": settings.resource_name,
            "author": settings.author,
            "description": settings.description,
            "model_mode": settings.model_mode,
            "scope": settings.export_scope,
            "export_placements": settings.export_placements,
            "collision_mode": settings.collision_mode,
            "export_dff": settings.export_dff,
            "export_txd": settings.export_txd,
            "copy_existing_assets": settings.copy_existing_assets,
            "source_assets_directory": bpy.path.abspath(settings.source_assets_directory),
            "default_parent_model_id": settings.default_parent_model_id,
            "replacement_start_id": settings.replacement_start_id,
            "default_interior": settings.default_interior,
            "default_dimension": settings.default_dimension,
            "use_map_interior": settings.use_map_interior,
            "default_lod_distance": settings.default_lod_distance,
            "skip_lod": settings.skip_lod,
            "write_map_file": settings.write_map_file,
            "create_zip": settings.create_zip,
            "clean_output": settings.clean_output,
            "fail_on_missing_models": settings.fail_on_missing_models,
            "write_model_ids_to_scene": settings.write_model_ids_to_scene,
            "truncate_frame_names": settings.truncate_frame_names,
            "rw_version": 0x36003,
        }

        try:
            result = mta_io.export_mta_resource(options)
        except Exception as error:
            self.report({"ERROR"}, str(error))
            return {"CANCELLED"}

        if result.get("zip_path"):
            self.report(
                {"INFO"},
                "Exported %d model(s), %d placement(s): %s" % (
                    result["models"],
                    result["placements"],
                    result["zip_path"],
                ),
            )
        else:
            self.report(
                {"INFO"},
                "Exported %d model(s), %d placement(s): %s" % (
                    result["models"],
                    result["placements"],
                    result["resource_directory"],
                ),
            )

        return {"FINISHED"}


class IMPORT_OT_mta_resource(bpy.types.Operator, ImportHelper):
    bl_idname = "scene.demonff_import_mta_resource"
    bl_label = "Import MTA Lua / Map / Resource"
    bl_description = "Import DemonFF MTA resources, static createObject Lua, MTA map XML, or resource ZIP files"
    bl_options = {"REGISTER", "UNDO"}

    filename_ext = ".lua"
    filter_glob: bpy.props.StringProperty(
        default="*.lua;*.map;*.xml;*.zip",
        options={"HIDDEN"},
    )

    def execute(self, context):
        settings = context.scene.mta
        options = {
            "file_name": self.filepath,
            "collection_name": settings.import_collection_name,
            "use_imported_models": settings.import_use_models,
            "import_resource_models": settings.import_resource_models,
            "create_placeholders": settings.import_placeholders,
            "clear_existing": settings.import_clear_existing,
        }

        try:
            result = mta_io.import_mta_file(options)
        except Exception as error:
            self.report({"ERROR"}, str(error))
            return {"CANCELLED"}

        self.report(
            {"INFO"},
            "Imported %d placement(s), %d placeholder(s) into %s" % (
                result["imported"],
                result["placeholders"],
                result["collection"],
            ),
        )
        return {"FINISHED"}


class SCENE_PT_demonff_mta_io(bpy.types.Panel):
    bl_label = "DemonFF - MTA Lua I/O"
    bl_idname = "SCENE_PT_demonff_mta_io"
    bl_space_type = "PROPERTIES"
    bl_region_type = "WINDOW"
    bl_context = "scene"

    def draw(self, context):
        settings = context.scene.mta
        layout = self.layout

        resource_box = layout.box()
        resource_box.label(text="MTA Resource")
        resource_box.prop(settings, "resource_name")
        resource_box.prop(settings, "author")
        resource_box.prop(settings, "description")
        resource_box.prop(settings, "model_mode")
        resource_box.prop(settings, "export_scope")
        resource_box.prop(settings, "collision_mode")

        asset_box = layout.box()
        asset_box.label(text="Model Assets")
        row = asset_box.row(align=True)
        row.prop(settings, "export_dff")
        row.prop(settings, "export_txd")
        asset_box.prop(settings, "copy_existing_assets")
        if settings.copy_existing_assets:
            asset_box.prop(settings, "source_assets_directory")
        asset_box.prop(settings, "default_parent_model_id")
        if settings.model_mode == "REPLACE_EXISTING":
            asset_box.prop(settings, "replacement_start_id")
            asset_box.prop(settings, "write_model_ids_to_scene")
            asset_box.prop(settings, "write_map_file")
        asset_box.prop(settings, "truncate_frame_names")

        placement_box = layout.box()
        placement_box.label(text="Placements")
        placement_box.prop(settings, "export_placements")
        placement_box.prop(settings, "default_interior")
        placement_box.prop(settings, "use_map_interior")
        placement_box.prop(settings, "default_dimension")
        placement_box.prop(settings, "default_lod_distance")
        placement_box.prop(settings, "skip_lod")

        output_box = layout.box()
        output_box.label(text="Output")
        output_box.prop(settings, "clean_output")
        output_box.prop(settings, "fail_on_missing_models")
        output_box.prop(settings, "create_zip")
        output_box.operator("scene.demonff_export_mta_resource", icon="EXPORT")

        import_box = layout.box()
        import_box.label(text="Import Lua / Map / Resource")
        import_box.prop(settings, "import_collection_name")
        import_box.prop(settings, "import_use_models")
        import_box.prop(settings, "import_resource_models")
        import_box.prop(settings, "import_placeholders")
        import_box.prop(settings, "import_clear_existing")
        import_box.operator("scene.demonff_import_mta_resource", icon="IMPORT")


class OBJECT_PT_demonff_mta(bpy.types.Panel):
    bl_label = "DemonFF - MTA Object"
    bl_idname = "OBJECT_PT_demonff_mta"
    bl_space_type = "PROPERTIES"
    bl_region_type = "WINDOW"
    bl_context = "object"

    @classmethod
    def poll(cls, context):
        return context.object is not None

    def draw(self, context):
        settings = context.object.mta
        layout = self.layout

        layout.prop(settings, "model_key")
        layout.prop(settings, "target_model_id")
        layout.prop(settings, "parent_model_id")

        row = layout.row(align=True)
        row.prop(settings, "use_custom_interior")
        if settings.use_custom_interior:
            row.prop(settings, "interior", text="")

        row = layout.row(align=True)
        row.prop(settings, "use_custom_dimension")
        if settings.use_custom_dimension:
            row.prop(settings, "dimension", text="")

        layout.prop(settings, "lod_distance")
        layout.prop(settings, "double_sided")
        layout.prop(settings, "collisions_enabled")
        layout.prop(settings, "frozen")
        layout.prop(settings, "breakable")
        layout.prop(settings, "alpha")
        layout.prop(settings, "alpha_transparency")
        layout.prop(settings, "filtering_enabled")
